### ISSUE TITLE
UX Enhancement

### ISSUE THREAD

**Issue by Henry-Hong** [Henry-Hong/HHR-Clone-Chatbot#1]
### Description
Almost every features are working great but needs to improve UX further. Thinking about applying aminations, error boundaries, mobile optimization too. Belows are tasks need to be accomplished.

### Tasks
- [x] Applying Optimistic update using useOptimisitc (upper than react@v18.3)
- [x] Applying animation when brand new chat appeared
- [ ] Add New Logo
- [x] Applying image render logic
- [x] Image Prefetch - using preload API (react-dom@19.0.0-rc)
